name: Release ResourcePack

on:
  push:
    tags:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pack Files
        run: mkdir target | cat VERSION | xargs -I {} zip -r target/SymbolRepair-{}.zip assets pack.png pack.mcmeta
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Upload Zip files
          path: target/*
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            *.zip